# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: git config --global user.email "ruzhnikov.ivan@gmail.com"
      - run: git config --global user.name "IRuzhnikov"

      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'adopt'
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.GPG_KEY_CONTENTS }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish to Sonatype
        run: mvn release:clean release:prepare release:perform -Dgpg.passphrase=${{ secrets.SIGNING_PASSWORD }}
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        env:
          OSSRH_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.SIGNING_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
