# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: |
          git config --global user.email "ruzhnikov.ivan@gmail.com"
          git config --global user.name "IRuzhnikov"

      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      
      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        with:
          gpg_private_key: ${{ secrets.GPG_KEY_CONTENTS }}
          gpg_passphrase: ${{ secrets.SIGNING_PASSWORD }}
          nexus_username: ${{ secrets.SONATYPE_USERNAME }}
          nexus_password: ${{ secrets.SONATYPE_PASSWORD }}
