# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup SSH Keys and known_hosts (for version update commit release:prepare)
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 0400 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 0400 ~/.ssh/id_rsa.pub
    
      - name: Setup git user config (for version update commit release:prepare)
        run: |
          git config --global user.email "ruzhnikov.ivan@gmail.com"
          git config --global user.name "IRuzhnikov"
          
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}
          maven_profiles: release
          maven_goals_phases: clean release:clean release:prepare release:perform
